[package]
name = "selector"
version = "0.1.0"
authors = ["Tim Dévé <timdeve@users.noreply.github.com>"]
edition = "2018"

[dependencies]
enum_primitive = "0.1.1"
libc = "0.2.43"
num = "0.2.0"
terminal_size = { git = "https://github.com/TimDeve/terminal-size.git" }
termios = "0.3.1"
